### ISSUE TITLE
Test fails on GNU Hurd

### ISSUE THREAD

**Issue by PeterBBBBB** [johnsonjh/duma#172]
Builds OK on Hurd, but dumatest fails to run. Looks like it hits an exit(-1) somewhere, but there is no useful error message
[build.log](https://github.com/johnsonjh/duma/files/7344839/build.log)

Full log here
https://buildd.debian.org/status/fetch.php?pkg=duma&arch=hurd-i386&ver=2.5.21-2&stamp=1633376424&raw=0

**Comment by PeterBBBBB** [comment]
I’ve done some investigation, running up Hurd in a KVM.

All the test programs fail  (Console just shows ‘Killed’)  except for thread-test which runs just fine.

I attach a backtrace for dumatest. 
It looks like it goes into an infinite loop, repeating every 10 lines in the trace.
Probably blows the stack.

Hope this helps,
Peter 
 
[gdb.txt](https://github.com/johnsonjh/duma/files/9192404/gdb.txt)

**Comment by sthibaul** [comment]
Getting the top of the stack would allow to get the root cause of the assertion failure.
The infinite loop happens just because printf uses allocation, which triggers an assertion again, etc.

**Comment by PeterBBBBB** [comment]
Hopefully a more useful backtrace

[gdb.txt](https://github.com/johnsonjh/duma/files/9202531/gdb.txt)

**Comment by johnsonjh** [comment]
> Getting the top of the stack would allow to get the root cause of the assertion failure.
> The infinite loop happens just because printf uses allocation, which triggers an assertion again, etc.

Thanks for looking into this - I haven't yet had time to configure a good Hurd testing environment.

There are two ways to handle this case.

You could use a non-allocating printf function - we're doing this in other project that prints backtraces (and also uses DUMA) even in the case of OOM - for example see https://gitlab.com/dps8m/dps8m/-/tree/master/src/dpsprintf based on yasprintf.  This really increases the size of DUMA, so I likely won't go this route.

Would you be able to see if the failure still happens when you set one or both of `DUMA_DISABLE_BANNER` and `DUMA_OUTPUT_FILE` in the environment?

**Comment by PeterBBBBB** [comment]
The DUMA defines did not seem to make a difference, but I have again with Samuel's libc 2.33-9 and tests now work if DUMA_DISABLE_BANNER is set. Not tried DUMA_OUTPUT_FILE again yet.

Issue also discussed here 
(https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1016106)

**Comment by PeterBBBBB** [comment]
We have a fix now, in Hurd's libc.
Closing here.
